let
    Источник = Excel.Workbook(File.Contents("\\Fileserv\Sams\Obmen\ПДО\План производства 2020-2022\Исходные данные ERP\Планы закупок Today.xlsx"), null, true),
    TDSheet_Sheet = Источник{[Item="TDSheet",Kind="Sheet"]}[Data],
    #"Повышенные заголовки" = Table.PromoteHeaders(TDSheet_Sheet, [PromoteAllScalars=true]),
    #"Измененный тип" = Table.TransformColumnTypes(#"Повышенные заголовки",{{"Артикул", type text}, {"Номенклатура", type text}, {"План закупок", type text}, {"Назначение", type text}, {"Дата потребности", type date}, {"Количество по плану", type number}, {"Ответственный за закупку", type text}, {"Ответственный менеджер за покупки", type text}, {"Заказано (Количество)", type number}, {"Разница  (Кол-во по плану - Заказано)", Int64.Type}, {"Заказано (пуст. назначение)", type number}, {"Заказано (Сумма)", type number}, {"Плановая дата поставки", type date}, {"Оплачено", type number}, {"Поступило по заказу", type number}, {"Реквизит декорация", type any}}),
    #"Удаленные столбцы" = Table.RemoveColumns(#"Измененный тип",{"Реквизит декорация"}),
    #"Замененное значение" = Table.ReplaceValue(#"Удаленные столбцы",null,0,Replacer.ReplaceValue,{"Заказано (Количество)", "Разница  (Кол-во по плану - Заказано)", "Заказано (пуст. назначение)", "Заказано (Сумма)", "Оплачено", "Поступило по заказу"}),
    #"Добавлен пользовательский объект" = Table.AddColumn(#"Замененное значение", "Потребность1", each [Поступило по заказу]-[Количество по плану]),
    #"Измененный тип1" = Table.TransformColumnTypes(#"Добавлен пользовательский объект",{{"Потребность1", type number}}),
    #"Строки с примененным фильтром" = Table.SelectRows(#"Измененный тип1", each [Потребность1] < 0),
    #"Удаленные столбцы1" = Table.RemoveColumns(#"Строки с примененным фильтром",{"Потребность1", "Ответственный менеджер за покупки"}),
    #"Объединенные запросы" = Table.NestedJoin(#"Удаленные столбцы1", {"Назначение"}, Назначения, {"Назначение"}, "Назначения", JoinKind.LeftOuter),
    #"Развернутый элемент Назначения" = Table.ExpandTableColumn(#"Объединенные запросы", "Назначения", {"Заказ", "Дата заказа", "Тип заказа"}, {"Заказ", "Дата заказа", "Тип заказа"}),
    #"Удаленные столбцы2" = Table.RemoveColumns(#"Развернутый элемент Назначения",{"Номенклатура", "Разница  (Кол-во по плану - Заказано)", "Заказано (пуст. назначение)", "Заказано (Сумма)", "Оплачено"})
in
    #"Удаленные столбцы2"
