let
    Источник = Table.NestedJoin(fПротоколПДО2022, {"ЗК"}, fЗаказыКлиентовСУПЗ, {"Заказ клиента.Номер"}, "fЗаказыКлиентовСУПЗ", JoinKind.FullOuter),
    #"Развернутый элемент fЗаказыКлиентовСУПЗ" = Table.ExpandTableColumn(Источник, "fЗаказыКлиентовСУПЗ", {"Заказ клиента.Номер", "Этап заказа клиента", "Клиент", "Договор", "Цена включает НДС", "Согласован", "Стадия заказа", "Дата отгрузки", "Договор.Дата поставки по договору", "Договор.Сумма договора (с НДС)", "Договор.ГОЗ", "Валюта", "Менеджер", "Специалист отдела продаж", "Сумма документа"}, {"fЗаказыКлиентовСУПЗ.Заказ клиента.Номер", "fЗаказыКлиентовСУПЗ.Этап заказа клиента", "fЗаказыКлиентовСУПЗ.Клиент", "fЗаказыКлиентовСУПЗ.Договор", "fЗаказыКлиентовСУПЗ.Цена включает НДС", "fЗаказыКлиентовСУПЗ.Согласован", "fЗаказыКлиентовСУПЗ.Стадия заказа", "fЗаказыКлиентовСУПЗ.Дата отгрузки", "fЗаказыКлиентовСУПЗ.Договор.Дата поставки по договору", "fЗаказыКлиентовСУПЗ.Договор.Сумма договора (с НДС)", "fЗаказыКлиентовСУПЗ.Договор.ГОЗ", "fЗаказыКлиентовСУПЗ.Валюта", "fЗаказыКлиентовСУПЗ.Менеджер", "fЗаказыКлиентовСУПЗ.Специалист отдела продаж", "fЗаказыКлиентовСУПЗ.Сумма документа"}),
    #"1" = Table.TransformColumns(#"Развернутый элемент fЗаказыКлиентовСУПЗ",{{"ЗК", Text.Trim, type text}}),
    #"2" = Table.AddColumn(#"1", "_ЗК_Номер", each if [ЗК] = null then [fЗаказыКлиентовСУПЗ.Заказ клиента.Номер] else [ЗК]),
    #"3" = Table.TransformColumnTypes(#"2",{{"_ЗК_Номер", type text}}),
    #"4" = Table.RenameColumns(#"3",{{"Статус", "_ПЛС_Статус"}}),
    #"5" = Table.ReplaceValue(#"4",null,"Отсутствует",Replacer.ReplaceValue,{"_ПЛС_Статус"}),
    #"6" = Table.RemoveColumns(#"5",{"ЗК"}),
    #"7" = Table.TransformColumnTypes(#"6",{{"СП", type text}}),
    #"8" = Table.RenameColumns(#"7",{{"Priority", "_ПЛС_тип"}}),
    #"9" = Table.ReplaceValue(#"8",null,"Отсутствует",Replacer.ReplaceValue,{"_ПЛС_тип"}),
    #"10" = Table.AddColumn(#"9", "_ЗК_Заказчик", each if [fЗаказыКлиентовСУПЗ.Клиент] = null then [Заказчик] else [fЗаказыКлиентовСУПЗ.Клиент]),
    #"11" = Table.TransformColumnTypes(#"10",{{"_ЗК_Заказчик", type text}}),
    #"12" = Table.AddColumn(#"11", "_ЗК_Договор", each if [fЗаказыКлиентовСУПЗ.Договор] = null then [Договор] else [fЗаказыКлиентовСУПЗ.Договор]),
    #"13" = Table.TransformColumnTypes(#"12",{{"_ЗК_Договор", type text}}),
    #"14" = Table.RenameColumns(#"13",{{"fЗаказыКлиентовСУПЗ.Специалист отдела продаж", "_СУПЗ_Специалист"}, {"fЗаказыКлиентовСУПЗ.Менеджер", "_СУПЗ_Менеджер"}, {"fЗаказыКлиентовСУПЗ.Валюта", "_ЗК_Валюта"}, {"fЗаказыКлиентовСУПЗ.Договор.ГОЗ", "_ЗК_ДоговорГОЗ"}}),
    #"15" = Table.RemoveColumns(#"14",{"fЗаказыКлиентовСУПЗ.Договор.Сумма договора (с НДС)"}),
    #"16" = Table.RenameColumns(#"15",{{"fЗаказыКлиентовСУПЗ.Договор.Дата поставки по договору", "_ЗК_Договор_ДатаПоставкиПоДоговору"}, {"fЗаказыКлиентовСУПЗ.Дата отгрузки", "_ЗК_ДатаОтгрузкиERP"}, {"fЗаказыКлиентовСУПЗ.Стадия заказа", "_СУПЗ_СтадияЗК"}, {"fЗаказыКлиентовСУПЗ.Согласован", "_СУПЗ_СогласованиеЗК"}}),
    #"17" = Table.RemoveColumns(#"16",{"fЗаказыКлиентовСУПЗ.Цена включает НДС", "fЗаказыКлиентовСУПЗ.Договор", "fЗаказыКлиентовСУПЗ.Клиент"}),
    #"18" = Table.RenameColumns(#"17",{{"fЗаказыКлиентовСУПЗ.Этап заказа клиента", "_СУПЗ_ЭтапЗК"}}),
    #"19" = Table.RemoveColumns(#"18",{"fЗаказыКлиентовСУПЗ.Заказ клиента.Номер"}),
    #"20" = Table.RenameColumns(#"19",{{"Документальная реализация", "_ПЛС_Документальная реализация"}, {"Доставлено", "_ПЛС_Доставлено"}, {"Отгружено с СГП", "_ПЛС_Отгружено с СГП"}, {"Сдано на СГП", "_ПЛС_Сдано на СГП"}, {"Дата выдачи в ОВ2/СМП", "_ПЛС_Дата выдачи"}, {"Дата комплектования (не позднее)", "_ПЛС_Дата комплектования"}, {"Объект", "_ПЛС_Объект"}, {"Условия отгрузки", "_ПЛС_УсловияОтгрузки"}, {"Условие выполнения договора", "_ПЛС_УсловияДоговора"}, {"Комментарий по заказу клента", "_ПЛС_Комментарий"}, {"Статус выполнения", "_ПЛС_СтатусВыполнения"}, {"Дата исполнения Ф.12.1", "_ПЛС_ДатаИсполненияФ.12.1"}, {"Дата Ф.12.1", "_ПЛС_Дата Ф.12.1"}, {"Краткое описание", "_ПЛС_Краткое описание"}}),
    #"21" = Table.RemoveColumns(#"20",{"Заказчик", "Договор"}),
    #"22" = Table.RenameColumns(#"21",{{"СП", "_ПЛС_СП"}, {"ВП", "_ПЛС_ВП"}, {"fЗаказыКлиентовСУПЗ.Сумма документа", "_ЗК_Сумма с НДС"}}),
    #"Переупорядоченные столбцы" = Table.ReorderColumns(#"22",
    
    {
        
                "_ЗК_Номер",
                "_ЗК_Заказчик", 
                "_ЗК_Договор",
                "_ЗК_Договор_ДатаПоставкиПоДоговору", 
                "_ЗК_ДоговорГОЗ", 
                "_ЗК_Сумма с НДС",
                "_ЗК_Валюта",
                "_ЗК_ДатаОтгрузкиERP",

        "_СУПЗ_ЭтапЗК",
        "_СУПЗ_СтадияЗК",
        "_СУПЗ_СогласованиеЗК",
        "_СУПЗ_Менеджер", 
        "_СУПЗ_Специалист",

        "_ПЛС_Статус", 
        "_ПЛС_СП", 
        "_ПЛС_тип", 
        "_ПЛС_ВП", 
        "_ПЛС_Краткое описание", 
        "_ПЛС_Дата Ф.12.1", 
        "_ПЛС_ДатаИсполненияФ.12.1", 
        "_ПЛС_СтатусВыполнения", 
        "_ПЛС_Комментарий", 
        "_ПЛС_УсловияДоговора", 
        "_ПЛС_УсловияОтгрузки", 
        "_ПЛС_Объект", 
        "_ПЛС_Дата комплектования", 
        "_ПЛС_Дата выдачи", 
        "_ПЛС_Сдано на СГП", 
        "_ПЛС_Отгружено с СГП", 
        "_ПЛС_Доставлено", 
        "_ПЛС_Документальная реализация"
 
        
        }),
    #"Добавлен пользовательский объект" = Table.AddColumn(#"Переупорядоченные столбцы", "Консолидированная дата", each if [_ПЛС_ДатаИсполненияФ.12.1] = null then [_ЗК_ДатаОтгрузкиERP] else [_ПЛС_ДатаИсполненияФ.12.1]),
    #"Измененный тип" = Table.TransformColumnTypes(#"Добавлен пользовательский объект",{{"Консолидированная дата", type date}}),
    #"Вставленный текст перед разделителем" = Table.AddColumn(#"Измененный тип", "Текст перед разделителем", each Text.BeforeDelimiter([_ПЛС_Статус], " "), type text),
    #"Переименованные столбцы" = Table.RenameColumns(#"Вставленный текст перед разделителем",{{"Текст перед разделителем", "Консолидированный статус производства"}})
in
    #"Переименованные столбцы"
