let
    Источник = Excel.Workbook(File.Contents("\\FILESERV\Sams\Obmen\ПДО\План производства 2020-2022\Исходные данные ERP\Отчет по ЗК 2022 (XLSX).xlsx"), null, true),
    TDSheet_Sheet = Источник{[Item="TDSheet",Kind="Sheet"]}[Data],
    #"Строки с примененным фильтром" = Table.SelectRows(TDSheet_Sheet, each ([Column5] <> null)),
    #"Повышенные заголовки" = Table.PromoteHeaders(#"Строки с примененным фильтром", [PromoteAllScalars=true]),
    #"Другие удаленные столбцы" = Table.SelectColumns(#"Повышенные заголовки",{"Заказ клиента.Номер", "Этап заказа клиента", "Клиент", "Договор", "Цена включает НДС", "Согласован", "Стадия заказа", "Дата отгрузки", "Договор.Дата поставки по договору", "Договор.Сумма договора (с НДС)", "Договор.ГОЗ 275ФЗ", "Тип заказа", "Валюта", "Тип рынка", "Менеджер", "Специалист отдела продаж", "Сумма документа"}),
    #"Измененный тип" = Table.TransformColumnTypes(#"Другие удаленные столбцы",{{"Заказ клиента.Номер", type text}, {"Этап заказа клиента", type text}, {"Клиент", type text}, {"Договор", type text}, {"Цена включает НДС", type text}, {"Согласован", type text}, {"Стадия заказа", type text}, {"Дата отгрузки", type date}, {"Договор.Дата поставки по договору", type date}, {"Договор.Сумма договора (с НДС)", type number}, {"Сумма документа", type number}, {"Договор.ГОЗ 275ФЗ", type text}, {"Валюта", type text}, {"Менеджер", type text}, {"Специалист отдела продаж", type text}}),
    #"Извлеченный текст перед разделителем" = Table.TransformColumns(#"Измененный тип", {{"Менеджер", each Text.BeforeDelimiter(_, " "), type text}, {"Специалист отдела продаж", each Text.BeforeDelimiter(_, " "), type text}}),
    #"Измененный тип1" = Table.TransformColumnTypes(#"Извлеченный текст перед разделителем",{{"Тип рынка", type text}, {"Тип заказа", type text}}),
    #"Строки с примененным фильтром1" = Table.SelectRows(#"Измененный тип1", each ([Тип заказа] = "Серийное производство")),
    #"Удаленные столбцы" = Table.RemoveColumns(#"Строки с примененным фильтром1",{"Тип заказа", "Тип рынка"})
in
    #"Удаленные столбцы"
