let
    Источник = Table.NestedJoin(_fЗаказыКлиентовТовары, {"Заказ клиента.Номер", "Идентификатор строки (РЗД)"}, _fЗаказыКлиентовСостав, {"Заказ клиента.Номер", "Идентификатор строки товары"}, "_fЗаказыКлиентовСостав", JoinKind.LeftOuter),
    #"Развернутый элемент _fЗаказыКлиентовСостав" = Table.ExpandTableColumn(Источник, "_fЗаказыКлиентовСостав", {"Идентификатор строки товары", "Номенклатура.Артикул", "Количество", "Количество (общ.)"}, {"_fЗаказыКлиентовСостав.Идентификатор строки товары", "_fЗаказыКлиентовСостав.Номенклатура.Артикул", "_fЗаказыКлиентовСостав.Количество", "_fЗаказыКлиентовСостав.Количество (общ.)"}),
    #"Удаленные столбцы1" = Table.RemoveColumns(#"Развернутый элемент _fЗаказыКлиентовСостав",{"Идентификатор строки (РЗД)"}),
    #"Строки с примененным фильтром" = Table.SelectRows(#"Удаленные столбцы1", each ([#"Количество (в единицах хранения)"] <> null and [#"Количество (в единицах хранения)"] <> 0)),
    #"Удаленные столбцы2" = Table.RemoveColumns(#"Строки с примененным фильтром",{"_fЗаказыКлиентовСостав.Количество (общ.)"}),
    #"Добавлен пользовательский объект" = Table.AddColumn(#"Удаленные столбцы2", "АртикулЗК", each if [_fЗаказыКлиентовСостав.Количество] = null then [#"Номенклатура.Артикул"] else [#"_fЗаказыКлиентовСостав.Номенклатура.Артикул"]),
    #"Измененный тип" = Table.TransformColumnTypes(#"Добавлен пользовательский объект",{{"АртикулЗК", type text}}),
    #"Добавлен пользовательский объект1" = Table.AddColumn(#"Измененный тип", "Кол-воЗК", each if [#"_fЗаказыКлиентовСостав.Номенклатура.Артикул"] = null then [#"Количество (в единицах хранения)"] else [#"Количество (в единицах хранения)"]*[_fЗаказыКлиентовСостав.Количество]),
    #"Измененный тип1" = Table.TransformColumnTypes(#"Добавлен пользовательский объект1",{{"Кол-воЗК", type number}}),
    #"Удаленные столбцы3" = Table.RemoveColumns(#"Измененный тип1",{"Номенклатура.Артикул", "Количество (в единицах хранения)", "_fЗаказыКлиентовСостав.Номенклатура.Артикул", "_fЗаказыКлиентовСостав.Количество"}),
    #"Переименованные столбцы" = Table.RenameColumns(#"Удаленные столбцы3",{{"Заказ клиента.Номер", "КлючЗК"}}),
    #"Добавлен пользовательский объект2" = Table.AddColumn(#"Переименованные столбцы", "Дата", each DateTime.LocalNow()),
    #"Измененный тип2" = Table.TransformColumnTypes(#"Добавлен пользовательский объект2",{{"Дата", type date}}),
    #"Удаленные столбцы" = Table.RemoveColumns(#"Измененный тип2",{"_fЗаказыКлиентовСостав.Идентификатор строки товары", "Дата"})
in
    #"Удаленные столбцы"
